### ISSUE TITLE
Idea: onTask offTask OneTask

### ISSUE THREAD

**Issue by stefanpenner** [ember-lifeline/ember-lifeline#58] opened 2018-01-08 23:14 UTC
Just a quick sketch before I forget:

it is not uncommon to leak event emitter handles, for example:

```js
export default Component.extend({
  init() {
    this._super(...arguments);
    this.lookup('service:router').on('didTransition', this.something); 
  },

  something() { }
})
```

We must remember to add the symmetric `off`

```js
destroy() {
    this.lookup('service:router').off('didTransition', this.something); 
}
```

But then we refactor to bind `this.something` and we once again leak.

```js
export default Component.extend({
  init() {
    this._super(...arguments);
    this.lookup('service:router').on('didTransition', this.something.bind(this)); 
  },
  destroy() {
    this.lookup('service:router').off('didTransition', this.something); 
  },
 something() { }

})
```

To correct this, we must also save of the bound method:

```js
export default Component.extend({
  init() {
    this._super(...arguments);
     this._boundSomething = this.something.bind(this)
    this.lookup('service:router').on('didTransition', this._boundSomething ); 
  },
  destroy() {
    this.lookup('service:router').off('didTransition', this._boundSomething); 
  },
 something() { }

})
```

Which is both verbose and a constant source of bugs.

Instead, it would be nice if we had some lifeline aware emitter (I have no idea what to call it, but lets call it `onTask`, `oneTask` and `offTask` for this example).

```js
this.onTask(emitter, eventName, callback); // emitter.on(eventName, callback) but lifeline entangled
this.oneTask(emitter, eventName, otherCallback); // emitter.one(eventName, callback) but lifeline entangled
this.offTask(emitter, eventName, callback);  // emitter.off(eventName, callback) but lifeline entangled
```

Full example becomes:

And as a bonus, arrow functions work!!

```js
export default Component.extend({
  init() {
    this._super(...arguments);
    this.onTask(this.lookup('service:router'), 'didTransition', () => this.something());
  },
 something() { }

})
``````

**Comment by scalvert** [comment] 2018-01-09 16:38
Thanks for this, @stefanpenner. I like this idea, though have some questions about the API.

1. Why do we need `offTask`? Shouldn't that be handled by lifeline itself? Essentially, if you use `onTask` to bind an event, lifeline should take care of the `offTask` part for you. Can you provide an example where I'd want to use `offTask` as a public method?
2. Are we thinking that lifeline would provide the mechanism of tracking the `eventEmitter`, `eventName`, and `callback`, similar to our other mixins? Essentially, it keeps track of the references, and auto-destroys?
3. Does it feel weird to add a `ContextBoundEventEmitterMixin`, where that mixin is not being mixed into a class that actually is an event emitter itself, but merely a container for providing an API to coordinate event emitter work? What I mean is, in your example above, `service:router` is actually the event emitter, and the containing component is merely the class whereby the event emitter instance is looked up/acted upon. 

Either way, these are minor details.

@rwjblue, thoughts?

**Comment by stefanpenner** [comment] 2018-01-09 16:53
> Why do we need offTask? Shouldn't that be handled by lifeline itself? Essentially, if you use onTask to bind an event, lifeline should take care of the offTask part for you. Can you provide an example where I'd want to use offTask as a public method?

Lifeline in general provides a  "maximum upper bound" on the "life" of something, in this case a handler attached to an event emitter. But application logic may require a shorter lifetime.

Super contrived example, but should do the trick:

Scenarios:
* if the class is destroyed, the event emitter handler it added to` this.uploadManager` is removed
* if the upload completes, the event emitter handler it added to` this.uploadManager` is removed

**Note: token based `off` may make more sense **

```js
export default class {
  uploadFile(file) {
    let uploader = this.uploadManager.
    let upload = uploader.upload(file);
    let token = this.onTask(upload, 'progress', progress => this.set('progress', progress'));

    // also off the task when the upload completes
    upload.finally(() => this.offTask(token));
  }
}

```

**Comment by stefanpenner** [comment] 2018-01-09 16:56
> Does it feel weird to add a ContextBoundEventEmitterMixin, where that mixin is not being mixed into a class that actually is an event emitter itself, but merely a container for providing an API to coordinate event emitter work? What I mean is, in your example above, service:router is actually the event emitter, and the containing component is merely the class whereby the event emitter instance is looked up/acted upon.


This seems weird for the following reasons:

* the general rule of "you created it, you clean it up" is violated, the event emitter should not become aware of the callers object lifetime.
* We can't mixin to every possible event emitter

**Comment by scalvert** [comment] 2018-01-09 18:29
> Lifeline in general provides a "maximum upper bound" on the "life" of something, in this case a handler attached to an event emitter. But application logic may require a shorter lifetime.

I can be convinced this API is necessary _if_ we're proceeding with the notion that the containing class is a coordinator of the work. That is, if we do in fact implement a `ContentBoundEventEmitterMixin`, and allow it to expose APIs that enable the lifecycle management of code within that class.

Due to the fact that you also feel it's weird to dispose of bound events you don't own, I'm not sure what the correct path is here. While I think it provides value to have a class act as the coordinator of event bindings, it does seem to violate ownership principles. However, if we treat this as an API that acts as a coordinator, and we're clear about this both in the naming conventions and the documentation, I think it would be OK.

What do you think about this?

**Comment by stefanpenner** [comment] 2018-01-09 18:48
Tangentially related: we may want to consider a lifeline namespace, so we don't keep polluting `this`

```js
this.lifeline.run
this.lifeline.on(emitter, eventName, callback)
```
cc @rwjblue

**Comment by stefanpenner** [comment] 2018-01-09 18:50
> What do you think about this?

I'm not totally sure what your describing.

**Comment by rwjblue** [comment] 2018-01-09 19:03
agree RE: namespace, though I was thinking of making the APIs more "functional" (e.g. more like `Ember.get` than `this.get`)...

**Comment by stefanpenner** [comment] 2018-01-09 19:07
@rwjblue yup that works:

```js
lifeline(this).on(this.lookup('service:router'), eventName, callback);

// vs

this.lifeline.on(this.lookup('service:router'), eventName, callback);
```

**Comment by BryanCrotaz** [comment] 2018-04-09 05:33
Add my vote for this style of API:
```
export default class {
  uploadFile(file) {
    let uploader = this.uploadManager.
    let upload = uploader.upload(file);
    let token = this.onTask(upload, 'progress', progress => this.set('progress', progress));

    // also off the task when the upload completes
    upload.finally(() => this.offTask(token));
  }
}
```
I have exactly this scenario throughout my app with the added `bind` problem. The cause of soooo many bugs.

**Comment by scalvert** [comment] 2022-01-31 23:48
Just doing a bit of cleanup on issues in this repo. If this issue is closed in error please reopen!

**Closed by scalvert** 2022-01-31 23:48 UTC
Labels: enhancement
